//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stanford_ShopOnline.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public Nullable<double> Price { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Approved_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Distributor_Id { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsBestSale { get; set; }
        public string ImageUrl1 { get; set; }
        public string ImageUrl2 { get; set; }
        public string ImageUrl3 { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Distributor Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
